version: "3"

services:
  oms:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - ./server:/go/src/server
    ports:
      - "1323:1323"
    tty: true 
    # networks:
      # - questar_order_management_system_backend
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oms 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    restart: always
  phpmyadmin:
    container_name: oms-pma
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8080:80
# networks:
#   questar_order_management_system_backend:
#     external: true
