// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCustomerParts(t *testing.T) {
	t.Parallel()

	query := CustomerParts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCustomerPartsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomerPartsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CustomerParts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomerPartsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CustomerPartSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCustomerPartsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CustomerPartExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CustomerPart exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CustomerPartExists to return true, but got false.")
	}
}

func testCustomerPartsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	customerPartFound, err := FindCustomerPart(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if customerPartFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCustomerPartsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CustomerParts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCustomerPartsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CustomerParts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCustomerPartsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	customerPartOne := &CustomerPart{}
	customerPartTwo := &CustomerPart{}
	if err = randomize.Struct(seed, customerPartOne, customerPartDBTypes, false, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}
	if err = randomize.Struct(seed, customerPartTwo, customerPartDBTypes, false, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = customerPartOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = customerPartTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CustomerParts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCustomerPartsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	customerPartOne := &CustomerPart{}
	customerPartTwo := &CustomerPart{}
	if err = randomize.Struct(seed, customerPartOne, customerPartDBTypes, false, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}
	if err = randomize.Struct(seed, customerPartTwo, customerPartDBTypes, false, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = customerPartOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = customerPartTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func customerPartBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func customerPartAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CustomerPart) error {
	*o = CustomerPart{}
	return nil
}

func testCustomerPartsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CustomerPart{}
	o := &CustomerPart{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, customerPartDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CustomerPart object: %s", err)
	}

	AddCustomerPartHook(boil.BeforeInsertHook, customerPartBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	customerPartBeforeInsertHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.AfterInsertHook, customerPartAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	customerPartAfterInsertHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.AfterSelectHook, customerPartAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	customerPartAfterSelectHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.BeforeUpdateHook, customerPartBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	customerPartBeforeUpdateHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.AfterUpdateHook, customerPartAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	customerPartAfterUpdateHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.BeforeDeleteHook, customerPartBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	customerPartBeforeDeleteHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.AfterDeleteHook, customerPartAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	customerPartAfterDeleteHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.BeforeUpsertHook, customerPartBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	customerPartBeforeUpsertHooks = []CustomerPartHook{}

	AddCustomerPartHook(boil.AfterUpsertHook, customerPartAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	customerPartAfterUpsertHooks = []CustomerPartHook{}
}

func testCustomerPartsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCustomerPartsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(customerPartColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCustomerPartsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCustomerPartsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CustomerPartSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCustomerPartsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CustomerParts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	customerPartDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`}
	_                   = bytes.MinRead
)

func testCustomerPartsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(customerPartPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(customerPartAllColumns) == len(customerPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCustomerPartsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(customerPartAllColumns) == len(customerPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CustomerPart{}
	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, customerPartDBTypes, true, customerPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(customerPartAllColumns, customerPartPrimaryKeyColumns) {
		fields = customerPartAllColumns
	} else {
		fields = strmangle.SetComplement(
			customerPartAllColumns,
			customerPartPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CustomerPartSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCustomerPartsUpsert(t *testing.T) {
	t.Parallel()

	if len(customerPartAllColumns) == len(customerPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLCustomerPartUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CustomerPart{}
	if err = randomize.Struct(seed, &o, customerPartDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CustomerPart: %s", err)
	}

	count, err := CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, customerPartDBTypes, false, customerPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CustomerPart struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CustomerPart: %s", err)
	}

	count, err = CustomerParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
