// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDocumentsTypes(t *testing.T) {
	t.Parallel()

	query := DocumentsTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDocumentsTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDocumentsTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DocumentsTypes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDocumentsTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DocumentsTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDocumentsTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DocumentsTypeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DocumentsType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DocumentsTypeExists to return true, but got false.")
	}
}

func testDocumentsTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	documentsTypeFound, err := FindDocumentsType(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if documentsTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDocumentsTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DocumentsTypes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDocumentsTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DocumentsTypes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDocumentsTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	documentsTypeOne := &DocumentsType{}
	documentsTypeTwo := &DocumentsType{}
	if err = randomize.Struct(seed, documentsTypeOne, documentsTypeDBTypes, false, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}
	if err = randomize.Struct(seed, documentsTypeTwo, documentsTypeDBTypes, false, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = documentsTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = documentsTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DocumentsTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDocumentsTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	documentsTypeOne := &DocumentsType{}
	documentsTypeTwo := &DocumentsType{}
	if err = randomize.Struct(seed, documentsTypeOne, documentsTypeDBTypes, false, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}
	if err = randomize.Struct(seed, documentsTypeTwo, documentsTypeDBTypes, false, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = documentsTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = documentsTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func documentsTypeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func documentsTypeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DocumentsType) error {
	*o = DocumentsType{}
	return nil
}

func testDocumentsTypesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DocumentsType{}
	o := &DocumentsType{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DocumentsType object: %s", err)
	}

	AddDocumentsTypeHook(boil.BeforeInsertHook, documentsTypeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	documentsTypeBeforeInsertHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.AfterInsertHook, documentsTypeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	documentsTypeAfterInsertHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.AfterSelectHook, documentsTypeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	documentsTypeAfterSelectHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.BeforeUpdateHook, documentsTypeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	documentsTypeBeforeUpdateHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.AfterUpdateHook, documentsTypeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	documentsTypeAfterUpdateHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.BeforeDeleteHook, documentsTypeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	documentsTypeBeforeDeleteHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.AfterDeleteHook, documentsTypeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	documentsTypeAfterDeleteHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.BeforeUpsertHook, documentsTypeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	documentsTypeBeforeUpsertHooks = []DocumentsTypeHook{}

	AddDocumentsTypeHook(boil.AfterUpsertHook, documentsTypeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	documentsTypeAfterUpsertHooks = []DocumentsTypeHook{}
}

func testDocumentsTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDocumentsTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(documentsTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDocumentsTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDocumentsTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DocumentsTypeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDocumentsTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DocumentsTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	documentsTypeDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`}
	_                    = bytes.MinRead
)

func testDocumentsTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(documentsTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(documentsTypeAllColumns) == len(documentsTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDocumentsTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(documentsTypeAllColumns) == len(documentsTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DocumentsType{}
	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, documentsTypeDBTypes, true, documentsTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(documentsTypeAllColumns, documentsTypePrimaryKeyColumns) {
		fields = documentsTypeAllColumns
	} else {
		fields = strmangle.SetComplement(
			documentsTypeAllColumns,
			documentsTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DocumentsTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDocumentsTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(documentsTypeAllColumns) == len(documentsTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLDocumentsTypeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DocumentsType{}
	if err = randomize.Struct(seed, &o, documentsTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DocumentsType: %s", err)
	}

	count, err := DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, documentsTypeDBTypes, false, documentsTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DocumentsType struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DocumentsType: %s", err)
	}

	count, err = DocumentsTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
