// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AdditionalInvoices", testAdditionalInvoicesUpsert)

	t.Run("Attachments", testAttachmentsUpsert)

	t.Run("Audits", testAuditsUpsert)

	t.Run("BusinessPartnerCompanies", testBusinessPartnerCompaniesUpsert)

	t.Run("Companies", testCompaniesUpsert)

	t.Run("CompaniesLogoes", testCompaniesLogoesUpsert)

	t.Run("Conditions", testConditionsUpsert)

	t.Run("ContractedCompanies", testContractedCompaniesUpsert)

	t.Run("CustomerParts", testCustomerPartsUpsert)

	t.Run("Cycles", testCyclesUpsert)

	t.Run("Documents", testDocumentsUpsert)

	t.Run("DocumentsTypes", testDocumentsTypesUpsert)

	t.Run("FailedJobs", testFailedJobsUpsert)

	t.Run("InvoiceForms", testInvoiceFormsUpsert)

	t.Run("Maintenances", testMaintenancesUpsert)

	t.Run("Migrations", testMigrationsUpsert)

	t.Run("OrderDates", testOrderDatesUpsert)

	t.Run("OrderItems", testOrderItemsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("PaymentDates", testPaymentDatesUpsert)

	t.Run("PaymentWays", testPaymentWaysUpsert)

	t.Run("PostagesLists", testPostagesListsUpsert)

	t.Run("ProductTypes", testProductTypesUpsert)

	t.Run("ProductsLists", testProductsListsUpsert)

	t.Run("Progresses", testProgressesUpsert)

	t.Run("PurchasedPostages", testPurchasedPostagesUpsert)

	t.Run("PurchasedProducts", testPurchasedProductsUpsert)

	t.Run("SeeParts", testSeePartsUpsert)

	t.Run("SellParts", testSellPartsUpsert)

	t.Run("SendWays", testSendWaysUpsert)

	t.Run("SiteRepresentatives", testSiteRepresentativesUpsert)

	t.Run("Sites", testSitesUpsert)

	t.Run("Users", testUsersUpsert)
}
