// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSellParts(t *testing.T) {
	t.Parallel()

	query := SellParts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSellPartsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSellPartsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SellParts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSellPartsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SellPartSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSellPartsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SellPartExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SellPart exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SellPartExists to return true, but got false.")
	}
}

func testSellPartsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	sellPartFound, err := FindSellPart(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if sellPartFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSellPartsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SellParts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSellPartsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SellParts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSellPartsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	sellPartOne := &SellPart{}
	sellPartTwo := &SellPart{}
	if err = randomize.Struct(seed, sellPartOne, sellPartDBTypes, false, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}
	if err = randomize.Struct(seed, sellPartTwo, sellPartDBTypes, false, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sellPartOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sellPartTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SellParts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSellPartsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	sellPartOne := &SellPart{}
	sellPartTwo := &SellPart{}
	if err = randomize.Struct(seed, sellPartOne, sellPartDBTypes, false, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}
	if err = randomize.Struct(seed, sellPartTwo, sellPartDBTypes, false, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sellPartOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sellPartTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func sellPartBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func sellPartAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SellPart) error {
	*o = SellPart{}
	return nil
}

func testSellPartsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SellPart{}
	o := &SellPart{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, sellPartDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SellPart object: %s", err)
	}

	AddSellPartHook(boil.BeforeInsertHook, sellPartBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	sellPartBeforeInsertHooks = []SellPartHook{}

	AddSellPartHook(boil.AfterInsertHook, sellPartAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	sellPartAfterInsertHooks = []SellPartHook{}

	AddSellPartHook(boil.AfterSelectHook, sellPartAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	sellPartAfterSelectHooks = []SellPartHook{}

	AddSellPartHook(boil.BeforeUpdateHook, sellPartBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	sellPartBeforeUpdateHooks = []SellPartHook{}

	AddSellPartHook(boil.AfterUpdateHook, sellPartAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	sellPartAfterUpdateHooks = []SellPartHook{}

	AddSellPartHook(boil.BeforeDeleteHook, sellPartBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	sellPartBeforeDeleteHooks = []SellPartHook{}

	AddSellPartHook(boil.AfterDeleteHook, sellPartAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	sellPartAfterDeleteHooks = []SellPartHook{}

	AddSellPartHook(boil.BeforeUpsertHook, sellPartBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	sellPartBeforeUpsertHooks = []SellPartHook{}

	AddSellPartHook(boil.AfterUpsertHook, sellPartAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	sellPartAfterUpsertHooks = []SellPartHook{}
}

func testSellPartsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSellPartsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(sellPartColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSellPartsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSellPartsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SellPartSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSellPartsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SellParts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	sellPartDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`}
	_               = bytes.MinRead
)

func testSellPartsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(sellPartPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(sellPartAllColumns) == len(sellPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSellPartsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(sellPartAllColumns) == len(sellPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SellPart{}
	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sellPartDBTypes, true, sellPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(sellPartAllColumns, sellPartPrimaryKeyColumns) {
		fields = sellPartAllColumns
	} else {
		fields = strmangle.SetComplement(
			sellPartAllColumns,
			sellPartPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SellPartSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSellPartsUpsert(t *testing.T) {
	t.Parallel()

	if len(sellPartAllColumns) == len(sellPartPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLSellPartUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SellPart{}
	if err = randomize.Struct(seed, &o, sellPartDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SellPart: %s", err)
	}

	count, err := SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, sellPartDBTypes, false, sellPartPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SellPart struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SellPart: %s", err)
	}

	count, err = SellParts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
